name: workflow-sample
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "This is a sample workflow"
      - run: |
            echo "Running some build steps..."
            echo "${{vars.project_env}}"
            echo "${{secrets.project_key}}"
    
  child:
    needs: build
    uses: ./.github/workflows/sampleworkflow2.yaml

  child2:
    needs: [build,child]
    uses: rajat430/childproj/.github/workflows/child1.yml@main
    with:
        name: "Rajat"